name: kostrov
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - ipykernel=6.25.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - openssl=3.0.12
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.10.13
  - python-dateutil=2.8.2
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - traitlets=5.7.1
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - asttokens==2.4.1
    - charset-normalizer==3.3.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fonttools==4.45.1
    - greenlet==3.0.1
    - idna==3.6
    - ipython==8.18.1
    - ipython-genutils==0.2.0
    - jedi==0.19.1
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lxml==4.9.3
    - matplotlib==3.7.0
    - nest-asyncio==1.5.8
    - numpy==1.23.5
    - packaging==23.2
    - pandas==1.5.3
    - pexpect==4.9.0
    - pillow==10.1.0
    - prompt-toolkit==3.0.41
    - pygments==2.17.2
    - pyparsing==3.1.1
    - pytz==2023.3.post1
    - pyzmq==25.1.1
    - requests==2.31.0
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - sqlalchemy==2.0.23
    - stack-data==0.6.3
    - threadpoolctl==3.2.0
    - tornado==6.4
    - typing-extensions==4.8.0
    - urllib3==2.1.0
    - wcwidth==0.2.12
